### ISSUE TITLE
Return value of Ideneal\EmailOctopus\Entity\MailingList::getId() must be of the type string, null returned

### ISSUE THREAD

**Issue by Nexx-Enterprpise** [Ideneal/EmailOctopus#2]
Getting this error:

Is there any way to resolve this 
Return value of Ideneal\EmailOctopus\Entity\MailingList::getId() must be of the type string, null returned

**Comment by Ideneal** [comment]
It seems strange. Could you put a piece of code to repeat the issue, please?
